name: main CD

on:
  push:
    branches: [ main ]

jobs:

  continuous_deployment:
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.IMAGE_NAME }}:$GITHUB_SHA
      - name: Push the Docker image
        run: docker push ${{ secrets.IMAGE_NAME }}:$GITHUB_SHA
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: newebpay-integration
          image: ${{ secrets.IMAGE_NAME }}:$GITHUB_SHA
          region: ${{ secrets.CLOUD_RUN_REGION }}
